
server:
  port: 8090
spring:
  security:
    enabled: false
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: users
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: root
    password: HoslDiBm5:DodLoPost
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



