eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: dima853
spring:
  cloud:
    config:
      override-system-properties: false